### ISSUE TITLE
Performance issues with many cats

### ISSUE THREAD

**Issue by TheShark27** [chris-blay/AndroidNougatEasterEgg#3] opened 2018-02-22 23:05 UTC
Hello,
I have collected 97 cats, and now the scrolling is really laggy. The app has become unresponsive, just like the default Easter Egg has done.
Here's an example: https://youtu.be/qwjeTbgZKKE

Wouldn't it be better to add different pages of cats, or empty circles with the cats' color where the cat appears once the drawable is ready?
Thank you

**Comment by chris-blay** [comment] 2018-02-24 04:10
Duplicate of #2

**Closed** 2018-02-24 04:10 UTC
Labels: duplicate

**Comment by TheShark27** [comment] 2018-02-25 18:35
Ok, but may I know if it's possible to fix it?
